apiVersion: v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: mcrusers
  name: mcrusers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mcrusers
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: mcrusers
    spec:
      containers:
        - env:
            - name: MONGO_DB
              value: microservices
            - name: MONGO_HOSTNAME
              value: users-mongo
            - name: MONGO_PASSWORD
              value: db
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: db
          image: users
          name: users
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
