apiVersion: v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: gui
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: gui
    spec:
      containers:
        - image: buckybuck/mcrvue
          name: gui
          ports:
            - containerPort: 80
              name: gui
          resources: {}
      restartPolicy: Always
status: {}

